Repository erica-likelion/spring-festival-client, pull requests merged in 2025-05, with the labels that each got.

#92 Tab Nav 색상 미반영, Nav Icon width height 미설정 해결
  src/components/tab-nav/TabNav.styles.ts
  src/layout/nav/nav-item.tsx
Labels: fix

#89 fix: SearchNavBar 수정
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/NavBar.types.ts
Labels: fix

#90 주점 랭킹 탭 UI/UX
  src/assets/icons/arrow-dropdown.svg
  src/assets/icons/arrow-dropup.svg
  src/assets/icons/heart.svg
  src/assets/icons/refresh.svg
  src/components/refresh-button/RefreshButton.styles.ts
  src/components/refresh-button/RefreshButton.tsx
  src/components/refresh-button/index.ts
  src/features/pub-rank/components/PubRank.styles.ts
  src/features/pub-rank/components/PubRank.tsx
  src/features/pub-rank/components/RankImageTextFrame.styles.ts
  src/features/pub-rank/components/RankImageTextFrame.tsx
  src/pages/booth/Booth.styles.ts
  src/pages/booth/Booth.tsx
  src/stores/useRefreshStore.ts
Labels: feature

#95 주점 리스트 UI
  src/assets/icons/alert-filled.svg
  src/assets/icons/alert.svg
  src/features/alarm/components/Alert.styles.ts
  src/features/alarm/components/Alert.tsx
  src/features/alarm/index.ts
  src/features/alarm/stores/useAlarmStore.ts
  src/features/booth/components/BoothList.styles.ts
  src/features/booth/components/BoothList.tsx
  src/features/booth/index.ts
  src/pages/booth/Booth.tsx
Labels: feature

#97 .env 깃무시 및 지도 관련 선언파일 추가
  .gitignore
  src/types/kakao-maps.d.ts
Labels: feature

#98 indicator 구현
  src/components/indicator/Indicator.style.ts
  src/components/indicator/Indicator.tsx
  src/components/indicator/Indicator.types.ts
  src/components/indicator/index.ts
  src/utils/calculateDotScale.ts
  src/utils/calculateVisibleDots.ts
Labels: feature

#102 상세정보 페이지 key값 입력 & $ 접두사 붙이기
  src/pages/performance/PerformanceDetail.styles.ts
  src/pages/performance/PerformanceDetail.tsx
Labels: fix

#103 transition $ 접두사 추가
  src/pages/performance/TimeTable.styles.ts
  src/pages/performance/TimeTable.tsx
Labels: fix

#100 fix: notification 컴포넌트 아이콘 import 형식으로 변경
  src/components/notification/Notification.tsx
Labels: fix

#101 공연 페이지 구현
  src/assets/icons/help_gy600.svg
  src/assets/icons/time_gy200.svg
  src/assets/images/performance/day1-newjeans.webp
  src/constants/performance/SingerInfo.ts
  src/features/performance/Carousel.styles.ts
  src/features/performance/Carousel.tsx
  src/features/performance/Carousel.types.ts
  src/features/performance/ModalHelp.styles.ts
  src/features/performance/ModalHelp.tsx
  src/features/performance/index.ts
  src/pages/performance/Performance.styles.ts
  src/pages/performance/Performance.tsx
  src/pages/performance/index.ts
Labels: feature

#110 NavBar 뒤로가기 backPath prop 추가
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/NavBar.types.ts
Labels: fix

#115 캐러셀 애니메이션 수정
  src/assets/images/performance/day1-newjeans.webp
  src/assets/images/performance/day1-seventeen.webp
  src/constants/performance/SingerInfo.ts
  src/features/performance/Carousel.styles.ts
  src/features/performance/Carousel.tsx
Labels: feature, fix

#116 타임테이블 여백 제거 및 언마운트 시 내브바 다시 생성
  src/pages/performance/TimeTable.styles.ts
  src/pages/performance/TimeTable.tsx
Labels: fix

#112 [공통 컴포넌트]Image Text Frame 활성화 스타일 여부 속성 추가
  src/components/image-text-frame/ImageTextFrame.styles.ts
  src/components/image-text-frame/ImageTextFrame.types.ts
  src/components/image-text-frame/ImageTextFrameWithOrganization.tsx
  src/components/image-text-frame/ImageTextFrameWithTime.tsx
Labels: feature

#118 feat: color 버튼 구현
  src/components/colorbuttons/ColorButton.style.ts
  src/components/colorbuttons/ColorButton.tsx
  src/components/colorbuttons/ColorButton.types.ts
  src/components/colorbuttons/index.ts
  src/styles/theme.ts
Labels: feature

#119 multitabs 추가
  src/components/tabs/Tabs.tsx
  src/components/tabs/Tabs.types.ts
  src/components/tabs/index.ts
Labels: feature, fix

#105 feat: bluebutton 구현
  src/components/bluebuttons/BlueButton.style.ts
  src/components/bluebuttons/BlueButton.tsx
  src/components/bluebuttons/BlueButton.types.ts
  src/components/bluebuttons/index.ts
Labels: feature

#109 [지도 페이지] 헤더 제작
  src/assets/icons/circle-checked.svg
  src/assets/icons/circle-unchecked.svg
  src/assets/icons/down-arrow.svg
  src/constants/map/Categories.ts
  src/constants/map/Days.ts
  src/constants/map/Z_INDEX.ts
  src/constants/map/index.ts
  src/features/map/header/Header.styles.ts
  src/features/map/header/Header.tsx
  src/features/map/header/Header.types.ts
  src/features/map/index.ts
  src/pages/Map.tsx
  src/pages/index.ts
  src/pages/map/MapPage.styles.ts
  src/pages/map/MapPage.tsx
  src/pages/map/MapPage.types.ts
Labels: feature

#126 분실물 메인 페이지 제작
  src/assets/icons/check.svg
  src/assets/icons/geopoint.svg
  src/constants/lost/LostItems.ts
  src/features/lost/components/main/ItemCard.styles.ts
  src/features/lost/components/main/ItemCard.tsx
  src/features/lost/components/main/ItemList.styles.ts
  src/features/lost/components/main/ItemList.tsx
  src/features/lost/components/main/ItemList.types.ts
  src/features/lost/components/main/Registration.styles.ts
  src/features/lost/components/main/Registration.tsx
  src/features/lost/components/main/StaffLabel.styles.ts
  src/features/lost/components/main/StaffLabel.tsx
  src/features/lost/components/main/StaffLabel.types.ts
  src/features/lost/index.ts
  src/features/lost/modal/ModalNotification.styles.ts
  src/features/lost/modal/ModalNotification.tsx
  src/features/lost/modal/ModalPost.styles.ts
  src/features/lost/modal/ModalPost.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/main/Lost.styles.ts
  src/pages/main/Lost.tsx
  src/pages/main/Main.tsx
Labels: feature

#129 [메인페이지] 이벤트 케러셀
  src/assets/icons/clock.svg
  src/assets/icons/cursor.svg
  src/assets/icons/pixel_moon.svg
  src/assets/icons/pixel_sun.svg
  src/constants/main/MainEvent.ts
  src/features/main/components/cards/EventCard.styles.ts
  src/features/main/components/cards/EventCard.tsx
  src/features/main/components/cards/EventCard.types.ts
  src/features/main/components/cards/Progress.styles.ts
  src/features/main/components/cards/Progress.tsx
  src/features/main/components/cards/index.ts
  src/features/main/components/carousels/EventCarousels.styles.ts
  src/features/main/components/carousels/EventCarousels.tsx
  src/features/main/components/carousels/EventCarouselsMotion.styles.ts
  src/features/main/components/carousels/index.ts
  src/pages/main/Main.styles.ts
  src/pages/main/Main.tsx
Labels: feature

#133 fix: svgr fill 속성 적용
  src/assets/icons/help_gy600.svg
  src/pages/performance/Performance.styles.ts
Labels: fix

#132 공지사항 리스트, 디테일 페이지
  package.json
  src/assets/images/notice/notice1-0.webp
  src/assets/images/notice/notice1-1.webp
  src/assets/images/notice/notice1-2.webp
  src/assets/images/notice/notice1-3.webp
  src/assets/images/notice/notice1-4.webp
  src/assets/images/notice/notice1-5.webp
  src/constants/main/Notice.ts
  src/features/main/notice/Notice.types.ts
  src/features/main/notice/NoticeBody.styles.ts
  src/features/main/notice/NoticeBody.tsx
  src/features/main/notice/NoticeBox.styles.ts
  src/features/main/notice/NoticeBox.tsx
  src/features/main/notice/NoticeDetailCarousels.styles.ts
  src/features/main/notice/NoticeDetailCarousels.tsx
  src/features/main/notice/NoticeText.styles.ts
  src/features/main/notice/NoticeText.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/main/Notice.styles.ts
  src/pages/main/Notice.tsx
  src/pages/main/NoticeDetail.styles.ts
  src/pages/main/NoticeDetail.tsx
  src/utils/truncateText.ts
  yarn.lock
Labels: feature

#134 [페이지] 분실물 상세페이지 구현
  src/main.tsx
  src/pages/index.ts
  src/pages/main/LostPost.styles.ts
  src/pages/main/LostPost.tsx
  src/pages/main/LostPost.types.ts
Labels: feature

#137 fix: bluebutton 폰트 추가
  src/components/bluebuttons/BlueButton.style.ts
  src/components/bluebuttons/BlueButton.tsx
  src/components/bluebuttons/BlueButton.types.ts
  src/pages/Login.tsx
Labels: fix

#141 [공통 컴포넌트] Notification - onClose 콜백 함수 추가 및 타입 정의 수정
  src/components/notification/Notification.tsx
  src/components/notification/Notification.types.ts
Labels: feature

#145 fix: 분실물 메인페이지 뒤로가기 경로 설정
  src/pages/main/Lost.tsx
Labels: fix

#147 feat: bluebutton 사이즈 추가
  src/components/bluebuttons/BlueButton.style.ts
  src/components/bluebuttons/BlueButton.types.ts
Labels: fix

#144 [페이지] 분실물 업로드 페이지 구현
  src/assets/icons/eclipse.svg
  src/assets/icons/nrk_camera.svg
  src/features/lost/components/upload/Description.styles.ts
  src/features/lost/components/upload/Description.tsx
  src/features/lost/components/upload/ImageSection.styles.ts
  src/features/lost/components/upload/ImageSection.tsx
  src/features/lost/components/upload/ImageSection.types.ts
  src/features/lost/components/upload/TimeSelect.styles.ts
  src/features/lost/components/upload/TimeSelect.tsx
  src/features/lost/components/upload/TimeSelect.types.ts
  src/features/lost/components/upload/Title.styles.ts
  src/features/lost/components/upload/Title.tsx
  src/features/lost/index.ts
  src/features/lost/modal/ModalCaution.styles.ts
  src/features/lost/modal/ModalCaution.tsx
  src/features/lost/modal/ModalCaution.types.ts
  src/features/lost/modal/ModalPost.styles.ts
  src/features/lost/modal/ModalPost.tsx
  src/hooks/useModal.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/main/lost/Lost.styles.ts
  src/pages/main/lost/Lost.tsx
  src/pages/main/lost/LostComplete.styles.ts
  src/pages/main/lost/LostComplete.tsx
  src/pages/main/lost/LostPost.styles.ts
  src/pages/main/lost/LostPost.tsx
  src/pages/main/lost/LostPost.types.ts
  src/pages/main/lost/LostUpload.styles.ts
  src/pages/main/lost/LostUpload.tsx
  src/styles/theme.ts
Labels: feature

#146 메인페이지 메뉴섹션
  src/constants/main/ExternalLink.ts
  src/features/main/components/menu/Menu.styles.ts
  src/features/main/components/menu/Menu.tsx
  src/features/main/components/menu/index.ts
  src/features/main/components/notice/Notice.types.ts
  src/features/main/components/notice/NoticeBody.styles.ts
  src/features/main/components/notice/NoticeBody.tsx
  src/features/main/components/notice/NoticeBox.styles.ts
  src/features/main/components/notice/NoticeBox.tsx
  src/features/main/components/notice/NoticeDetailCarousels.styles.ts
  src/features/main/components/notice/NoticeDetailCarousels.tsx
  src/features/main/components/notice/NoticeText.styles.ts
  src/features/main/components/notice/NoticeText.tsx
  src/features/main/components/notice/index.ts
  src/pages/index.ts
  src/pages/main/Main.styles.ts
  src/pages/main/Main.tsx
  src/pages/main/notice/Notice.styles.ts
  src/pages/main/notice/Notice.tsx
  src/pages/main/notice/NoticeDetail.styles.ts
  src/pages/main/notice/NoticeDetail.tsx
  src/pages/main/notice/index.ts
Labels: feature

#148 feat: 로그인 페이지 및 모달 구현
  src/assets/icons/kakaotalk.svg
  src/assets/images/hylight-likelion.svg
  src/features/login/components/LoginButton.style.ts
  src/features/login/components/LoginButton.tsx
  src/features/login/components/LoginButton.types.ts
  src/features/login/components/index.ts
  src/features/login/modal/LoginModal.style.ts
  src/features/login/modal/LoginModal.tsx
  src/features/login/modal/index.ts
  src/pages/Login.tsx
  src/pages/index.ts
  src/pages/login/Login.style.ts
  src/pages/login/Login.tsx
  src/pages/login/index.ts
Labels: feature

#149 BlueButton: 패딩 스타일 수정
  src/components/bluebuttons/BlueButton.style.ts
Labels: fix

#143 주점 상세 페이지 UI
  src/components/input-stepper/InputStepper.styles.ts
  src/components/input-stepper/InputStepper.tsx
  src/components/modal/Modal.tsx
  src/components/tab-nav/TabNav.styles.ts
  src/components/tab-nav/TabNav.tsx
  src/features/booth/components/BoothInfo.styles.ts
  src/features/booth/components/BoothInfo.tsx
  src/features/booth/components/BoothList.styles.ts
  src/features/booth/components/BoothList.tsx
  src/features/booth/components/BoothLocation.styles.ts
  src/features/booth/components/BoothLocation.tsx
  src/features/booth/components/MenuList.styles.ts
  src/features/booth/components/MenuList.tsx
  src/features/booth/index.ts
  src/features/index.ts
  src/features/like/components/LikeButton.styles.ts
  src/features/like/components/LikeButton.tsx
  src/features/like/index.ts
  src/features/rank/components/PubRank.styles.ts
  src/features/rank/components/PubRank.tsx
  src/features/rank/components/RankImageTextFrame.styles.ts
  src/features/rank/components/RankImageTextFrame.tsx
  src/features/rank/index.ts
  src/features/waiting/components/Waiting.styles.ts
  src/features/waiting/components/Waiting.tsx
  src/features/waiting/components/WaitingModal.styles.ts
  src/features/waiting/components/WaitingModal.tsx
  src/features/waiting/index.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/booth/Booth.tsx
  src/pages/booth/BoothDetail.styles.ts
  src/pages/booth/BoothDetail.tsx
  src/pages/index.ts
  src/stores/useModalStore.ts
  src/utils/newlineToBr.ts
Labels: feature

#157 바텀 네비게이션 색상 및 크기 수정
  src/assets/icons/home.svg
  src/assets/icons/pub.svg
  src/assets/icons/stage.svg
  src/assets/icons/waiting.svg
  src/layout/nav/Nav.tsx
  src/layout/nav/nav-item.tsx
Labels: fix

#160 주점 상세 페이지 미적용 수정
  src/components/input-stepper/InputStepper.styles.ts
  src/features/booth/components/BoothLocation.styles.ts
  src/features/booth/components/BoothLocation.tsx
  src/features/waiting/components/WaitingModal.tsx
Labels: fix

#156 나의 예약 페이지 - 웨이팅 결과 없음
  src/assets/icons/hanyang_yeh.svg
  src/features/waiting/components/NoWaitingResult.tsx
  src/features/waiting/components/NowaitingResult.styles.ts
  src/features/waiting/index.ts
  src/pages/User.tsx
Labels: feature

#161 테이블링 리스트 카드
  src/features/waiting/components/TablingCardList.styles.ts
  src/features/waiting/components/TablingCardList.tsx
  src/features/waiting/index.ts
  src/pages/User.tsx
  src/pages/index.ts
  src/pages/user/User.styles.ts
  src/pages/user/User.tsx
Labels: feature

#151 공지사항 슬라이더 컴포넌트
  src/constants/main/Notice.ts
  src/features/main/components/cards/NoticeCard.styles.ts
  src/features/main/components/cards/NoticeCard.tsx
  src/features/main/components/notice/Notice.types.ts
  src/features/main/components/slider/NoticeSlider.styles.ts
  src/features/main/components/slider/NoticeSlider.tsx
  src/features/main/components/slider/index.ts
  src/pages/main/Main.tsx
Labels: feature

#167 [페이지] 만든이들 페이지 구현
  src/constants/main/Members.ts
  src/features/main/components/madeby/Card.styles.ts
  src/features/main/components/madeby/Card.tsx
  src/features/main/components/madeby/Card.types.ts
  src/features/main/components/madeby/index.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/main/notice/MadeBy.styles.ts
  src/pages/main/notice/MadeBy.tsx
Labels: feature

#169 fix: 사진 수정
  src/assets/icons/hanyang_v4.svg
  src/pages/main/lost/LostComplete.tsx
Labels: fix

#165 웨이팅 취소 모달
  src/components/bluebuttons/BlueButton.style.ts
  src/components/bluebuttons/BlueButton.tsx
  src/components/bluebuttons/BlueButton.types.ts
  src/components/colorbuttons/ColorButton.style.ts
  src/components/colorbuttons/ColorButton.tsx
  src/components/modal/Modal.tsx
  src/features/waiting/components/TablingCardList.tsx
  src/features/waiting/components/WaitingCancelModal.styles.ts
  src/features/waiting/components/WaitingCancelModal.tsx
  vite.config.ts
Labels: feature

#168 무한 좋아요 애니메이션
  src/assets/lotties/multiple_like.json
  src/assets/lotties/once_like.json
  src/features/booth/components/BoothInfo.tsx
  src/features/like/components/LikeButton.styles.ts
  src/features/like/components/LikeButton.tsx
Labels: feature

#171 테이블링 카드 디자인 피드백 반영
  src/features/waiting/components/TablingCardList.styles.ts
  src/features/waiting/components/TablingCardList.tsx
  src/pages/user/User.styles.ts
  src/pages/user/User.tsx
Labels: feature, fix

#173 스플래시 이후 흰화면 로딩 문제
  index.html
  src/main.tsx
  vite.config.ts
Labels: bug, fix

#174 [지도] 바텀시트 with 더미데이터 Ver.2
  src/assets/icons/clock.svg
  src/components/image-text-frame/ImageTextFrameWithTime.tsx
  src/constants/map/BottomSheetOptions.ts
  src/constants/map/DummyData.ts
  src/features/map/bottomsheet/BottomSheet.styles.ts
  src/features/map/bottomsheet/BottomSheet.tsx
  src/features/map/bottomsheet/BottomSheet.types.ts
  src/features/map/index.ts
  src/hooks/useBottomSheet.ts
  src/pages/map/MapPage.styles.ts
  src/pages/map/MapPage.tsx
Labels: feature

#163 [페이지] 분실물 검색 페이지
  src/constants/search/SEARCH_CONSTANTS.ts
  src/features/lost/components/main/NoResultMessage.styles.ts
  src/features/lost/components/main/NoResultMessage.tsx
  src/features/lost/components/main/SkeletonCard.styles.ts
  src/features/lost/components/main/SkeletonCard.tsx
  src/features/lost/index.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/main/lost/LostSearch.styles.ts
  src/pages/main/lost/LostSearch.tsx
Labels: feature

#176 fix: 데이터에 따른 block 적용
  src/constants/performance/SingerList.ts
  src/pages/performance/TimeTable.styles.ts
  src/pages/performance/TimeTable.tsx
Labels: fix

#175 [지도 페이지] 카테고리별 알림관리 기능
  src/constants/map/CATEGORIES.ts
  src/constants/map/CategoryNotifications.ts
  src/constants/map/DAYS.ts
  src/constants/map/DummyData.ts
  src/constants/map/index.ts
  src/features/map/bottomsheet/BottomSheet.styles.ts
  src/features/map/bottomsheet/BottomSheet.tsx
  src/features/map/bottomsheet/BottomSheet.types.ts
  src/pages/map/MapPage.tsx
  src/stores/useNotificationStore.ts
Labels: feature

#178 메인페이지 구현
  src/assets/icons/Background-Reflect.svg
  src/assets/icons/Background-main.svg
  src/assets/icons/clock.svg
  src/assets/icons/form_logo.svg
  src/assets/icons/instagram.svg
  src/assets/icons/lion_logo.svg
  src/assets/icons/lionlove_logo.svg
  src/assets/icons/lost_logo.svg
  src/assets/icons/student_logo.svg
  src/components/image-text-icon-frame/ImageTextIconFrame.styles.ts
  src/components/nav-bar/NavBar.styles.ts
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/NavBar.types.ts
  src/features/main/components/cards/NoticeCard.styles.ts
  src/features/main/components/cards/NoticeCard.tsx
  src/features/main/components/carousels/EventCarouselsMotion.styles.ts
  src/features/main/components/menu/Menu.styles.ts
  src/features/main/components/menu/Menu.tsx
  src/features/main/components/notice/Notice.types.ts
  src/features/main/components/notice/NoticeBody.styles.ts
  src/features/main/components/slider/NoticeSlider.styles.ts
  src/features/main/components/slider/NoticeSlider.tsx
  src/features/main/components/user/Footer.styles.ts
  src/features/main/components/user/Footer.tsx
  src/features/main/components/user/UserLogin.styles.ts
  src/features/main/components/user/UserLogin.tsx
  src/features/main/components/user/index.ts
  src/pages/index.ts
  src/pages/main/Main.styles.ts
  src/pages/main/Main.tsx
  src/pages/main/made/MadeBy.styles.ts
  src/pages/main/made/MadeBy.tsx
  src/pages/main/made/index.ts
Labels: feature

#179 공연 페이지 아티스트 수정
  src/assets/images/performance/day1-10cm.webp
  src/assets/images/performance/day1-ftisland.webp
  src/assets/images/performance/day1-idle.webp
  src/assets/images/performance/day1-kino.webp
  src/assets/images/performance/day2-davichi.webp
  src/assets/images/performance/day2-highlight.webp
  src/assets/images/performance/day2-jackpot.webp
  src/assets/images/performance/day3-chungha.webp
  src/assets/images/performance/day3-dj.webp
  src/assets/images/performance/day3-ifeye.webp
  src/assets/images/performance/day3-yb.webp
  src/assets/images/performance/song-list/chungha-1.webp
  src/assets/images/performance/song-list/chungha-2.webp
  src/assets/images/performance/song-list/chungha-3.webp
  src/assets/images/performance/song-list/davichi-1.webp
  src/assets/images/performance/song-list/davichi-2.webp
  src/assets/images/performance/song-list/davichi-3.webp
  src/assets/images/performance/song-list/dj-1.webp
  src/assets/images/performance/song-list/dj-2.webp
  src/assets/images/performance/song-list/dj-3.webp
  src/assets/images/performance/song-list/ftisland-1.webp
  src/assets/images/performance/song-list/ftisland-2.webp
  src/assets/images/performance/song-list/ftisland-3.webp
  src/assets/images/performance/song-list/highlight-1.webp
  src/assets/images/performance/song-list/highlight-2.webp
  src/assets/images/performance/song-list/highlight-3.webp
  src/assets/images/performance/song-list/idle-1.webp
  src/assets/images/performance/song-list/idle-2.webp
  src/assets/images/performance/song-list/idle-3.webp
  src/assets/images/performance/song-list/ifeye-1.webp
  src/assets/images/performance/song-list/ifeye-2.webp
  src/assets/images/performance/song-list/ifeye-3.webp
  src/assets/images/performance/song-list/jackpot-1.webp
  src/assets/images/performance/song-list/jackpot-2.webp
  src/assets/images/performance/song-list/jackpot-3.webp
  src/assets/images/performance/song-list/kino-1.webp
  src/assets/images/performance/song-list/kino-2.webp
  src/assets/images/performance/song-list/kino-3.webp
  src/assets/images/performance/song-list/tencm-1.webp
  src/assets/images/performance/song-list/tencm-2.webp
  src/assets/images/performance/song-list/tencm-3.webp
  src/assets/images/performance/song-list/yb-1.webp
  src/assets/images/performance/song-list/yb-2.webp
  src/assets/images/performance/song-list/yb-3.webp
  src/constants/performance/ImageMap.ts
  src/constants/performance/SingerInfo.ts
  src/constants/performance/SingerList.ts
  src/features/performance/Carousel.styles.ts
  src/features/performance/Carousel.tsx
  src/features/performance/ModalHelp.styles.ts
  src/features/performance/ModalHelp.tsx
Labels: fix

#180 feat: 로그인 배경 추가
  src/assets/images/login-bg.svg
  src/pages/login/Login.style.ts
Labels: feature

#181 [지도 페이지] 지도 기본 연동
  src/assets/icons/my-location.svg
  src/assets/icons/re-center-clicked.svg
  src/assets/icons/re-center.svg
  src/hooks/useKakaoMap.ts
  src/pages/map/MapPage.styles.ts
  src/pages/map/MapPage.tsx
  src/pages/map/MapPage.types.ts
  src/types/kakao-maps.d.ts
Labels: feature

#185 [지도 페이지] 현재 날짜 기반 자동 일차 적용
  src/constants/festival/dates.ts
  src/pages/map/MapPage.tsx
  src/utils/dateUtils.ts
Labels: feature

#186 카카오 로그인 구현
  index.html
  package.json
  src/assets/lotties/loading.json
  src/lib/AxiosInstance.ts
  src/lib/index.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/login/Login.tsx
  src/pages/login/Redirection.style.ts
  src/pages/login/Redirection.tsx
  src/pages/login/index.ts
  src/pages/main/Main.tsx
  src/stores/useAuthStore.ts
  src/types/kakao-login.d.ts
  yarn.lock
Labels: feature

#188 [API] 분실물 페이지 API 연결
  src/constants/lost/LostItems.ts
  src/features/lost/components/main/ItemCard.tsx
  src/features/lost/components/main/ItemList.tsx
  src/features/lost/components/main/ItemList.types.ts
  src/features/lost/components/main/Registration.tsx
  src/lib/AxiosInstance.ts
  src/pages/main/lost/LostPost.tsx
  src/pages/main/lost/LostSearch.tsx
  src/pages/main/lost/LostUpload.tsx
Labels: feature

#198 fix: 외부링크 및 내부 링크 수정
  src/constants/performance/SingerInfo.ts
  src/pages/performance/Performance.tsx
Labels: fix

#201 FCM Web Push 알람 구현
  .env-development
  .env-production
  package.json
  public/firebase-messaging-sw.js
  src/features/waiting/components/TablingCardList.tsx
  src/features/waiting/stores/useWaitingStore.ts
  src/layout/Layout.tsx
  src/layout/main/Main.tsx
  src/lib/AxiosInstance.ts
  src/main.tsx
  src/services/alarm.ts
  src/services/fcm/firebase.ts
  src/services/fcm/foregroundMessage.ts
  src/services/fcm/notificationPermission.ts
  src/services/login.ts
  src/services/registerServiceWorker.ts
  src/services/waiting.db.ts
  vite.config.ts
  yarn.lock
Labels: feature

#203 아이콘, 파비콘, 프로젝트 제목 변경
  index.html
  public/favicon.ico
  public/icons/icon-128x128.webp
  public/icons/icon-144x144.webp
  public/icons/icon-152x152.webp
  public/icons/icon-192x192.webp
  public/icons/icon-256x256.webp
  public/icons/icon-384x384.webp
  public/icons/icon-48x48.webp
  public/icons/icon-512x512.webp
  public/icons/icon-72x72.webp
  public/icons/icon-96x96.webp
  vite.config.ts
Labels: feature

#206 무한 좋아요 (구독 알림설정)
  src/assets/icons/nrk_arrow-dropdown.svg
  src/constants/booth/booth.ts
  src/features/like/components/LikeButton.tsx
  src/features/like/libs/rank.ts
  src/features/like/stores/useLikeStore.ts
  src/features/rank/components/PubRank.tsx
  src/features/rank/components/RankImageTextFrame.styles.ts
  src/features/rank/components/RankImageTextFrame.tsx
  src/features/waiting/components/WaitingModal.tsx
  src/features/waiting/stores/useWaitingStore.ts
  src/layout/Layout.tsx
  src/services/like/like.db.ts
  src/services/like/like.ts
  src/services/waiting/waiting.db.ts
  src/services/waiting/waiting.ts
  src/types/like.type.ts
Labels: feature

#207 style,fix: 아이콘 수정 및 제목과 부제목 너비 변경
  src/assets/icons/clock.svg
  src/components/image-text-frame/ImageTextFrame.styles.ts
Labels: fix

#208 [API] 공연 알림 API 연동
  src/constants/performance/SingerInfo.ts
  src/features/alarm/components/Alert.tsx
  src/features/alarm/stores/useAlarmStore.ts
  src/features/performance/Carousel.tsx
  src/features/performance/Carousel.types.ts
  src/services/alarm.ts
Labels: feature

#210 비로그인 사용자 차단 기능
  src/features/login/modal/LoginModal.tsx
  src/features/lost/components/main/Registration.tsx
  src/features/main/components/user/Footer.tsx
  src/hooks/useModal.ts
  src/layout/nav/Nav.tsx
  src/pages/user/User.tsx
Labels: feature

#217 main framer motion animate 제거
  src/layout/main/Main.tsx
Labels: fix

#222 fix: safari standalone 모달 안뜨게 처리
  src/features/main/components/user/AppInstallPrompt.tsx
Labels: fix

#220 [지도] 마커 초기화 로직 및 선택 시 UI 구현
  src/constants/map/LOC_DATA.ts
  src/constants/map/MapData.ts
  src/features/map/bottomsheet/BottomSheet.styles.ts
  src/hooks/useBottomSheet.ts
  src/hooks/useKakaoMap.ts
  src/pages/map/MapPage.styles.ts
  src/pages/map/MapPage.tsx
  src/styles/marker.styles.ts
  src/types/kakao-maps.d.ts
  src/utils/markerIcons.ts
Labels: feature

#224 standalone 이면 설치 유도 모달 안뜨게 설정
  src/features/main/components/user/AppInstallPrompt.tsx
Labels: fix

#223 [페이지] 만든 이들 페이지
  src/assets/images/madeby/hj_1.svg
  src/assets/images/madeby/hs_1.svg
  src/assets/images/madeby/jh_1.svg
  src/assets/images/madeby/jm_1.svg
  src/assets/images/madeby/jw_1.svg
  src/assets/images/madeby/lg_1.svg
  src/assets/images/madeby/lge_1.svg
  src/assets/images/madeby/madeby_image.webp
  src/assets/images/madeby/madeby_logo.webp
  src/assets/images/madeby/sg_1.svg
  src/assets/images/madeby/sge_1.svg
  src/assets/images/madeby/sh_1.svg
  src/assets/images/madeby/sm_1.svg
  src/assets/images/madeby/sy_1.svg
  src/constants/main/Members.ts
  src/features/main/components/madeby/Card.styles.ts
  src/features/main/components/madeby/Card.tsx
  src/pages/main/made/MadeBy.styles.ts
  src/pages/main/made/MadeBy.tsx
Labels: fix

#226 fix: key props 루트로 이동
  src/pages/performance/TimeTable.tsx
Labels: bug, fix

#227 fix: noresultmessagetitle 적용
  src/features/lost/components/main/NoResultMessage.tsx
Labels: fix

#228 유저 first land flow 구성
  src/components/modal/Modal.style.ts
  src/features/alarm/components/AlarmModal.styles.ts
  src/features/alarm/components/AlarmModal.tsx
  src/features/main/components/user/AppInstallPrompt.styles.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/login/Login.tsx
  src/pages/main/Main.tsx
Labels: feature

#230 메인 메뉴 frame 로고 변경
  src/assets/icons/lion_logo.svg
  src/features/main/components/menu/Menu.tsx
Labels: fix

#233 [지도] 뒤로가기(초기화) 버튼 추가 및 관련 핸들러 구현
  src/features/map/header/Header.styles.ts
  src/features/map/header/Header.tsx
  src/features/map/header/Header.types.ts
  src/pages/map/MapPage.tsx
Labels: feature

#238 [지도] 검색기능 구현
  src/hooks/useDebounce.ts
  src/main.tsx
  src/pages/map/MapPage.tsx
  src/pages/map/SearchPage.styles.ts
  src/pages/map/SearchPage.tsx
Labels: feature

#237 주점 실시간 웨이팅 카운트 api 연동
  src/features/like/stores/useLikeStore.ts
  src/features/waiting/components/Waiting.tsx
  src/layout/Layout.tsx
  src/main.tsx
  src/services/waiting/waiting.ts
  src/types/like.type.ts
Labels: feature

#236 주점 오픈 알림 alert 버튼 제거
  src/features/booth/components/BoothList.tsx
Labels: feature

#239 [API] 공연 알림 해제
  src/components/tabs/Tabs.styles.ts
  src/features/alarm/components/Alert.tsx
  src/features/alarm/stores/useAlarmStore.ts
  src/pages/performance/Performance.tsx
  src/services/alarm.ts
Labels: feature

#240 [지도] 푸드트럭 및 플리마켓 구역 표시
  src/hooks/useKakaoMap.ts
  src/types/kakao-maps.d.ts
Labels: feature

#241 fix: padding bottom 100px로 변경
  src/pages/main/made/MadeBy.styles.ts
Labels: fix

#242 주점 메뉴 데이터 반영
  src/assets/images/booth/booth-locate.webp
  src/assets/images/booth/sport.webp
  src/components/image-text-frame/ImageTextFrame.types.ts
  src/components/image-text-frame/MenuFrame.tsx
  src/constants/booth/booth.ts
  src/features/booth/components/BoothInfo.tsx
  src/features/booth/components/BoothLocation.styles.ts
  src/features/booth/components/MenuList.tsx
Labels: feature

#251 축기단 수정사항 반영, QA 반영
  src/assets/images/booth/architecture-env-poster.webp
  src/assets/images/booth/architecture-env.webp
  src/assets/images/booth/insurance.webp
  src/constants/booth/booth.ts
  src/features/alarm/components/AlarmModal.tsx
  src/features/booth/components/MenuList.styles.ts
  src/features/booth/components/MenuList.tsx
  src/features/like/components/LikeButton.tsx
  src/layout/nav/nav-item.tsx
  src/main.tsx
  src/pages/booth/Booth.tsx
  src/pages/booth/BoothDetail.tsx
  src/pages/index.ts
  src/utils/priceFormatter.ts
Labels: feature

#257 QA반영(탭, 주점 디테일)
  src/pages/booth/Booth.tsx
  src/pages/booth/BoothDetail.tsx
Labels: fix

#261 하단 보더 제거 QA
  src/pages/booth/BoothDetail.styles.ts
  src/pages/booth/BoothDetail.tsx
Labels: feature, fix

#260 주점 QA
  src/components/image-text-frame/ImageTextFrame.styles.ts
  src/components/tab-nav/TabNav.styles.ts
  src/features/booth/components/BoothInfo.styles.ts
  src/features/booth/components/BoothInfo.tsx
  src/features/booth/components/BoothList.styles.ts
  src/features/booth/components/BoothLocation.styles.ts
  src/features/booth/components/BoothLocation.tsx
  src/features/booth/components/MenuList.styles.ts
  src/features/booth/components/MenuList.tsx
  src/features/like/components/LikeButton.styles.ts
  src/features/like/components/LikeButton.tsx
  src/features/rank/components/PubRank.styles.ts
  src/features/rank/components/RankImageTextFrame.styles.ts
  src/features/rank/components/RankImageTextFrame.tsx
  src/pages/booth/Booth.styles.ts
  src/pages/booth/BoothDetail.styles.ts
  src/pages/booth/BoothDetail.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: fix

#265 toggle추가
  src/features/booth/components/MenuList.tsx
Labels: fix

#264 NavBar fixed처리
  src/components/nav-bar/NavBar.styles.ts
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/pages/main/Main.styles.ts
  src/pages/main/made/MadeBy.styles.ts
Labels: fix

#271 fix: 블루버튼 사이즈 수정
  src/components/bluebuttons/BlueButton.style.ts
  src/components/bluebuttons/BlueButton.types.ts
Labels: fix

#266 [지도/검색] 최근검색기능 제거 및 추천검색어 변경
  src/components/nav-bar/NavBar.types.ts
  src/constants/search/SEARCH_CONSTANTS.ts
  src/pages/map/SearchPage.styles.ts
  src/pages/map/SearchPage.tsx
Labels: fix

#270 공지사항 업데이트(05.25기준)
  src/assets/images/notice/notice1 (1).webp
  src/assets/images/notice/notice25 (1).png
  src/assets/images/notice/notice25 (2).png
  src/assets/images/notice/notice25 (3).png
  src/assets/images/notice/notice25 (4).png
  src/assets/images/notice/notice25 (5).png
  src/assets/images/notice/notice25 (6).png
  src/constants/main/Notice.ts
  src/features/main/components/carousels/EventCarousels.tsx
  src/pages/performance/Performance.tsx
Labels: feature

#273 [지도] 주점 좌표 수정 및 Noti 너비 수정
  src/assets/icons/my-location.svg
  src/components/image-text-frame/ImageTextFrame.styles.ts
  src/constants/map/LOC_DATA.ts
  src/constants/map/MapData.ts
  src/features/map/bottomsheet/BottomSheet.tsx
Labels: fix

#278 searchnav width 조정
  src/components/nav-bar/NavBar.styles.ts
  src/components/nav-bar/NavBar.tsx
Labels: fix

#279 fix: 프론트 -> 프론트엔드로 변경
  src/constants/main/Members.ts
  src/pages/main/made/MadeBy.tsx
Labels: fix

#280 [수정사항] 주점 메뉴 오타 수정
  src/constants/booth/booth.ts
Labels: fix

#281 인앱 접속 시 사파리로 강제 이동
  index.html
  src/features/like/components/LikeButton.tsx
  src/utils/inAppValid.ts
Labels: feature

#284 fix: 융합시스템 오탈자 수정
  src/constants/booth/booth.ts
Labels: fix

#287 공연 이벤트 수정 및 한국시간 기준 이벤트 출력
  src/constants/main/MainEvent.ts
  src/features/main/components/carousels/EventCarousels.tsx
Labels: fix

#288 좋아요 버튼 z인덱스 추가
  src/features/like/components/LikeButton.styles.ts
  src/features/like/components/LikeButton.tsx
Labels: bug, fix

#289 index.html script 함수 제거
  index.html
Labels: fix

#292 tab container 배경색 추가, relative 포지션
  src/components/tab-nav/TabNav.styles.ts
  src/features/rank/components/PubRank.styles.ts
Labels: fix

#293 Funnel Main margin top 제거
  src/components/tab-nav/TabNav.styles.ts
  src/features/booth/components/BoothList.styles.ts
  src/features/rank/components/PubRank.styles.ts
  src/pages/booth/Booth.styles.ts
Labels: fix

#283 [지도] 위치 데이터 추가 및 헤더 오버레이 그라데이션 수정 + 버그수정
  src/assets/images/map/proteen.webp
  src/assets/images/map/stamp.webp
  src/constants/map/LOC_DATA.ts
  src/constants/map/MapData.ts
  src/constants/map/Z_INDEX.ts
  src/features/map/bottomsheet/BottomSheet.styles.ts
  src/features/map/header/Header.styles.ts
  src/features/map/header/Header.tsx
  src/pages/map/MapPage.styles.ts
  src/pages/map/MapPage.tsx
Labels: feature, fix, refact

#294 tab nav bottom underline bottom -1px로 변경
  src/components/tab-nav/TabNav.styles.ts
Labels: fix

#296 nct mark Artist 추가
  src/assets/images/performance/day1-mark.webp
  src/assets/images/performance/song-list/mark-1.webp
  src/assets/images/performance/song-list/mark-2.webp
  src/assets/images/performance/song-list/mark-3.webp
  src/constants/performance/ImageMap.ts
  src/constants/performance/SingerInfo.ts
Labels: feature

#297 공지사항 업데이트
  src/assets/images/notice/notice105 (1).png
  src/assets/images/notice/notice105 (2).png
  src/assets/images/notice/notice105 (3).png
  src/assets/images/notice/notice105 (4).png
  src/assets/images/notice/notice105 (5).png
  src/assets/images/notice/notice105 (6).png
  src/assets/images/notice/notice26 (1).png
  src/assets/images/notice/notice26 (2).png
  src/assets/images/notice/notice26 (3).png
  src/assets/images/notice/notice26 (4).png
  src/assets/images/notice/notice27 (1).png
  src/assets/images/notice/notice27 (10).png
  src/assets/images/notice/notice27 (11).png
  src/assets/images/notice/notice27 (12).png
  src/assets/images/notice/notice27 (2).png
  src/assets/images/notice/notice27 (3).png
  src/assets/images/notice/notice27 (4).png
  src/assets/images/notice/notice27 (5).png
  src/assets/images/notice/notice27 (6).png
  src/assets/images/notice/notice27 (7).png
  src/assets/images/notice/notice27 (8).png
  src/assets/images/notice/notice27 (9).png
  src/constants/main/Notice.ts
Labels: feature, fix

#298 Fix map path
  src/constants/map/MapData.ts
Labels: fix
