Repository erica-likelion/spring-festival-client, pull requests merged in 2025-04, with the labels that each got.

#6 Styled-components 기반 theme, globalStyle 설정/ stylelint 추가
  .husky/_/pre-commit
  package.json
  src/app/index.ts
  src/app/modules/styled.d.ts
  src/app/modules/svg.d.ts
  src/app/styles/global.ts
  src/app/styles/index.ts
  src/app/styles/theme.ts
  src/main.tsx
  stylelint.config.js
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#7 Main 병합 conflict 문제
  README.md
  yarn.lock
Labels: enhancement

#11 Feat:stylelint
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/pre-commit
  .stylelintrc
  package.json
  src/app/styles/global.ts
  src/app/styles/theme.ts
  stylelint.config.js
  yarn.lock
Labels: feature

#13 Feat husky
  .husky/_/h
  .husky/_/husky.sh
  .husky/commit-msg
  .husky/pre-commit
Labels: fix

#14 project architecture 구조 반영
  src/assets/index.ts
  src/components/index.ts
  src/constants/index.ts
  src/features/index.ts
  src/hooks/index.ts
  src/layout/index.ts
  src/main.tsx
  src/pages/index.ts
  src/services/index.ts
  src/styles/global.ts
  src/styles/index.ts
  src/styles/theme.ts
  src/types/styled.d.ts
  src/types/svg.d.ts
  src/utils/index.ts
  src/widgets/index.ts
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: feature

#15 peer dependency 반영, framer-motion, zustand 설치
  package.json
  yarn.lock
Labels: feature

#17 configuaret routing
  package.json
  src/layout/Layout.tsx
  src/layout/index.ts
  src/layout/nav/Nav.tsx
  src/layout/nav/index.ts
  src/main.tsx
  src/pages/Booth.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Map.tsx
  src/pages/Performance.tsx
  src/pages/index.ts
  yarn.lock
Labels: feature

#19 layout 구성
  index.html
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/layout/nav/Nav.styles.ts
  src/layout/nav/Nav.tsx
  src/layout/nav/nav.types.ts
  src/main.tsx
  src/pages/User.tsx
  src/pages/index.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/types/styled-components.d.ts
  tsconfig.node.json
  vite.config.ts
Labels: feature

#23 reload prevent
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/styles/global.ts
Labels: feature

#24 메인 영역 방지 -> 전역 처리로 변경
  src/layout/Layout.tsx
Labels: fix

#38 Navigation 바, Main 컴포넌트 화면 전환 기능 추가
  package.json
  src/assets/icons/geopoint.svg
  src/assets/icons/home.svg
  src/assets/icons/pub.svg
  src/assets/icons/stage.svg
  src/assets/icons/waiting.svg
  src/assets/lotties/geopoint-filled.json
  src/assets/lotties/home-filled.json
  src/assets/lotties/pub-filled.json
  src/assets/lotties/stage-filled.json
  src/assets/lotties/waiting-filled.json
  src/hooks/index.ts
  src/hooks/usePreviousPath.ts
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/layout/main/Main.styles.ts
  src/layout/main/Main.tsx
  src/layout/nav/Nav.tsx
  src/layout/nav/nav-item.tsx
  src/layout/nav/nav.types.ts
  src/main.tsx
  src/pages/User.tsx
  src/stores/index.ts
  src/stores/useLayoutStore.ts
  src/utils/history.ts
  src/utils/index.ts
  src/utils/moveAnimation.ts
  yarn.lock
Labels: feature

#40 PWA 다크 테마 스플래시 이후 흰 화면 깜빡임 현상 해결
  index.html
  src/styles/global.ts
Labels: feature, fix

#41 바텀 네비게이션 바 완료
  index.html
  src/assets/lotties/geopoint-blue-filled.json
  src/assets/lotties/geopoint-filled.json
  src/assets/lotties/home-blue-filled.json
  src/assets/lotties/home-filled.json
  src/assets/lotties/pub-blue-filled.json
  src/assets/lotties/pub-filled.json
  src/assets/lotties/stage-blue-filled.json
  src/assets/lotties/stage-filled.json
  src/assets/lotties/waiting-blue-filled.json
  src/assets/lotties/waiting-filled.json
  src/layout/nav/nav-item.tsx
  src/styles/global.ts
Labels: feature

#49 [공통 컴포넌트] Image_Text_Icon_Frame 완성
  src/assets/icons/right-arrow.svg
  src/components/image-text-icon-frame/ImageTextIconFrame.styles.ts
  src/components/image-text-icon-frame/ImageTextIconFrame.tsx
  src/components/image-text-icon-frame/ImageTextIconFrame.types.ts
  src/styles/theme.ts
Labels: feature

#51 Feat image text frame
  src/assets/icons/clock.svg
  src/components/image-text-frame/ImageTextFrame.styles.ts
  src/components/image-text-frame/ImageTextFrame.types.ts
  src/components/image-text-frame/ImageTextFrameWithOrganization.tsx
  src/components/image-text-frame/ImageTextFrameWithTime.tsx
  src/components/image-text-frame/MenuFrame.tsx
  src/utils/priceFormatter.ts
Labels: feature

#53 Tabs 컴포넌트 추가
  src/components/tabs/Tabs.styles.ts
  src/components/tabs/Tabs.tsx
  src/components/tabs/Tabs.types.ts
Labels: feature

#58 Fix -> style: 폰트 theme.ts 적용
  src/components/image-text-icon-frame/ImageTextIconFrame.styles.ts
Labels: fix

#61 fix: transparent 오타 수정
  src/components/tabs/Tabs.styles.ts
Labels: fix

#64 [공통컴포넌트] Tabs - 토글 기능(선택적) 추가 및 border 일관성
  src/components/tabs/Tabs.styles.ts
  src/components/tabs/Tabs.tsx
  src/components/tabs/Tabs.types.ts
Labels: feature

#54 Notification 컴포넌트 추가
  src/assets/icons/close.svg
  src/assets/images/notification.webp
  src/components/notification/Notification.styles.ts
  src/components/notification/Notification.tsx
  src/components/notification/Notification.types.ts
  src/types/css-values.ts
Labels: feature

#65 Chips 컴포넌트 구현
  src/assets/icons/close.svg
  src/components/chips/Chips.styles.ts
  src/components/chips/Chips.tsx
  src/components/chips/Chips.types.ts
  src/hooks/useChipClose.ts
Labels: feature

#69 NavBar 컴포넌트 구현
  src/assets/icons/Logo_Sample.svg
  src/assets/icons/left-arrow.svg
  src/assets/icons/search.svg
  src/components/nav-bar/NavBar.styles.ts
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/NavBar.type.ts
Labels: feature

#74 반응형 설계(브라우저 사이즈 처리, root 포지션 변경), 단위 변경(px -> rem)
  src/layout/nav/Nav.styles.ts
  src/layout/nav/Nav.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: feature

#81 [긴급] SVGR rem 크기 미반영 문제
  vite.config.ts
Labels: fix

#78 modularization 작업
  src/components/chips/index.ts
  src/components/image-text-frame/index.ts
  src/components/image-text-icon-frame/index.ts
  src/components/index.ts
  src/components/nav-bar/index.ts
  src/components/notification/index.ts
  src/components/tabs/index.ts
  src/hooks/index.ts
  src/layout/Layout.tsx
  src/layout/nav/Nav.tsx
  src/stores/index.ts
  src/utils/index.ts
Labels: feature, refact

#72 NavBar width값 추가 및 정렬 수정
  src/components/nav-bar/NavBar.styles.ts
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/NavBar.type.ts
Labels: fix

#71 [공용컴포넌트] 모달 컴포넌트, 커스텀 훅 + 로컬 폰트 추가
  public/fonts/SUIT-Bold.woff2
  public/fonts/SUIT-Medium.woff2
  public/fonts/SUIT-Regular.woff2
  public/fonts/SUIT-SemiBold.woff2
  src/assets/icons/nrk_close.svg
  src/assets/icons/nrk_help.svg
  src/components/modal/Modal.style.ts
  src/components/modal/Modal.tsx
  src/components/modal/index.ts
  src/hooks/useModal.ts
  src/main.tsx
  src/stores/useModalStore.ts
  src/styles/fonts.ts
  src/styles/global.ts
  src/styles/index.ts
  src/styles/theme.ts
  src/types/modal.type.ts
  src/utils/nanoid.ts
Labels: feature

#76 TabNav 컴포넌트, useFunnel 커스텀 훅
  src/components/notification/Notification.types.ts
  src/components/tab-nav/TabNav.styles.ts
  src/components/tab-nav/TabNav.tsx
  src/components/tab-nav/TabNav.type.ts
  src/components/tab-nav/index.ts
  src/hooks/useFunnel.tsx
  src/pages/Booth.tsx
  src/pages/booth/Booth.tsx
  src/pages/booth/booth.styles.ts
  src/pages/index.ts
  src/types/css-values.ts
  src/types/funnel.type.ts
Labels: feature

#82 input stepper 컴포넌트
  src/assets/icons/minus.svg
  src/assets/icons/plus.svg
  src/components/input-stepper/InputStepper.styles.ts
  src/components/input-stepper/InputStepper.tsx
  src/components/input-stepper/index.ts
Labels: feature

#86 Theme 자동 완성 미반영 문제
  src/types/styled-components.d.ts
Labels: bug, fix
